server:
  port: 13085
  servlet:
    context-path : /tmfew
spring:
  profiles: default
  application:
    name: openslice-service-ewsof
  servlet:
    multipart.max-file-size: 10MB
    multipart.max-request-size: 10MB
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
  security:
    oauth2:
      client:
        provider:
          authOpensliceProvider:
            token-uri: http://portal.openslice.io/osapi-oauth-server/oauth/token
        registration:
          authOpensliceProvider:
            client-id: osapiWebClientId
            client-secret: secret
            authorization-grant-type: client_credentials

logging:
  level:
    root: INFO
    portal.api: INFO
    org.springframework: INFO
    org.apache.camel: INFO 
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
    
oauthsign:
   key: "EK97Y7Y9WPGG1MEG"
   clientId: "osapiWebClientId"
   tokenSecret: "secret"
   scopes:
   - "openapi"
   - "admin"
   - "read"
   - "write"

#QUEUE MESSAGES  
CATALOG_GET_EXTERNAL_SERVICE_PARTNERS: "jms:queue:CATALOG.GET.EXTERNALSERVICEPARTNERS"
